---
title: "Urbanization and Environmental Quality in Arizona, USA"
subtitle: "INFO 523 - Final Project"
author: 
  - name: "Vera Jackson, Molly Kerwick, Brooke Pacheco"
    affiliations:
      - name: "College of Information Science, University of Arizona"
description: "Final Project for course INFO 523: Data Mining and Discovery"
format:
   html:
    code-tools: true
    code-overflow: wrap
    embed-resources: true
editor: visual
execute:
  warning: false
  echo: false
jupyter: python3
---

The goal of our project is to analyze the relationship between urbanization and environmental quality across regions within Arizona, identifying patterns and anomalies in how urban growth impacts climate metrics such as storms, temperature, and precipitation. As we have seen with the uproar by the Tucson population regarding the proposed environmental impacts of the Project Blue data center, environmental quality is important to local populations. We hope to use this study to identify the regional relationship between urbanization and climate indicators. We will be using traffic count data as our urbanization metric, and National Oceanographic and Atmospheric Administration (NOAA) climate and storm event data as our environmental quality data.

Watch our final presentation [here.](https://arizona.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ffb43bbf-9bd4-4159-97b1-b33f00364bfb)